#!/bin/bash

d=~/rawdisk2/sh
dhi="$d/org.kde.syntax-highlighting"

if [ ! -d "$dhi" ] ; then
  mkdir -p "$dhi/syntax" "$dhi/themes"
  cp ~/game/org.kde.syntax-highlighting/themes/my.theme "$dhi/themes"
fi

base=$PWD
for f in "$@"; do
  [ -f "$base/data/syntax/$f.xml" ] && ln -s "$base/data/syntax/$f.xml" "$dhi/syntax" || echo "$f" error
done
