#!/bin/bash

set -e

# base="$(realpath "$(dirname "$0")")"
# base="${base%/*}"
# cd "$base"

base="$PWD"

d=~/rawdisk2/sh

dhi="$d/org.kde.syntax-highlighting"
mkdir -p "$dhi" "$dhi/themes"
cp ~/game/org.kde.syntax-highlighting/themes/my.theme "$dhi/themes"

if [ $# -eq 0 ]; then
  ln -s "$base/data/syntax/" "$dhi"
else
  mkdir -p "$dhi/syntax"
  for f in "$@"; do
    [ -f "$base/data/syntax/$f.xml" ] && ln -s "$base/data/syntax/$f.xml" "$dhi/syntax" || echo "$f" error
  done
fi

ln -s "$base/"* "$d"
cd "$d"
rm CMakeLists.txt
sed 's#find_package(ECM 5[^ ]\+ REQUIRED NO_MODULE)#find_package(ECM 5.50.0 REQUIRED NO_MODULE)#;/include(ECMAddQch)/d' \
  "$base"/CMakeLists.txt > CMakeLists.txt

mkdir b
cd b

echo '#!/bin/sh
set -e
cd '"$PWD"'/autotests
for name in "$@" ; do
  if [ -r output/highlight.$name.ref ]; then
    name=highlight.$name
  fi
  echo copy $name
  cp output/$name.ref '"$base"'/autotests/reference/
  cp html.output/$name.html '"$base"'/autotests/html/
  cp folding.out/$name.fold '"$base"'/autotests/folding/
done' > update-reference-data.sh

echo '#!/bin/sh
XDG_DATA_DIRS='"$d"' vt-kate-syntax-highlighter -ctMy\ Breeze\ Dark "$@"' > hi.sh

echo '#!/bin/sh
XDG_DATA_DIRS='"$d"' RLWRAP_HOME='"$d"' rlwrap vt-kate-syntax-highlighter -ctMy\ Breeze\ Dark -us "$@"' > ihi.sh

echo '#!/bin/sh
XDG_DATA_DIRS='"$d"' ~/game/ksyntax-trace/vt-kate-syntax-highlighter -cntMy\ Breeze\ Dark "$@"' > nhi.sh

echo '#!/bin/sh
XDG_DATA_DIRS='"$d"' RLWRAP_HOME='"$d"' rlwrap ~/game/ksyntax-trace/vt-kate-syntax-highlighter -cntMy\ Breeze\ Dark -nus "$@"' > nihi.sh

echo '#!/bin/sh
XDG_DATA_DIRS='"$d"' ~/game/ksyntax-trace/vt-kate-syntax-highlighter-full -cxtMy\ Breeze\ Dark "$@"' > thi.sh

echo '#!/bin/sh
XDG_DATA_DIRS='"$d"' RLWRAP_HOME='"$d"' rlwrap ~/game/ksyntax-trace/vt-kate-syntax-highlighter-full -cntMy\ Breeze\ Dark -xus "$@"' > tihi.sh

echo '#!/bin/sh
XDG_DATA_DIRS='"$d"' kate "$@"' > kate.sh

echo '#!/bin/sh
if [ $# -eq 1 ]; then
  ninja && XDG_DATA_DIRS='"$d"' ctest --output-on-failure --rerun-failed
else
  ninja && XDG_DATA_DIRS='"$d"' ctest --output-on-failure
fi' > test.sh

chmod +x update-reference-data.sh hi.sh ihi.sh thi.sh tihi.sh nhi.sh nihi.sh test.sh kate.sh

ln -s "$base"/autotests/input/ "$base"/data/syntax/ .

# [ $# -eq 1 ] && cmake -DCMAKE_BUILD_TYPE=Release -G Ninja ..

echo -e '\e[33m'
echo "cd $d/b"
echo 'cmake -DCMAKE_BUILD_TYPE=Release -G Ninja ..'
echo './hi input/'
echo './test.sh'
echo './update-reference-data.sh <lang>'
echo
