#!/usr/bin/env bash

set -e

# base="$(realpath "$(dirname "$0")")"
# base="${base%/*}"
# cd "$base"

cd "$(dirname $0)"/../syntax-highlighting
base="$PWD"

d=~/rawdisk2/sh

dhi="$d/org.kde.syntax-highlighting"
mkdir -p "$d/b" "$d/src/lib" "$dhi/themes"
cp ~/game/org.kde.syntax-highlighting/themes/my.theme "$dhi/themes"

errcode=0
if [[ $# -eq 0 ]]; then
  ln -s "$base/data/syntax/" "$dhi"
else
  mkdir -p "$dhi/syntax"
  cd data/syntax
  for f in "$@"; do
    if [[ ! -f "$f.xml" ]]; then
      echo "$f: file not found"
      ((++errcode))
      continue
    fi

    ln -s "$PWD/$f.xml" "$dhi/syntax" || ((++errcode))
  done
  cd ../..
fi

shopt -s extglob

ln -s "$base/"!(src|CMakeLists.txt) "$d"
ln -s "$base/src/"!(lib|CMakeLists.txt) "$d/src"
ln -s "$base/src/lib/"!(CMakeLists.txt) "$d/src/lib"

cd "$d"

sed 's#find_package(ECM 5[^ ]\+ REQUIRED NO_MODULE)#find_package(ECM 5.66.0 REQUIRED NO_MODULE)#;/include(ECMAddQch)/d' \
  "$base"/CMakeLists.txt > CMakeLists.txt

sed '/^ecm_qt_install_logging_categories/,/^)/d' \
  "$base"/src/CMakeLists.txt > src/CMakeLists.txt

sed '/^    DESCRIPTION "Syntax Highlighting"/d;/^    EXPORT KSYNTAXHIGHLIGHTING/d' \
  "$base"/src/lib/CMakeLists.txt > src/lib/CMakeLists.txt

cd b

echo '#!/bin/sh
set -e
cd '"$PWD"'/autotests
for name in "$@" ; do
  if [ -r output/highlight.$name.ref ]; then
    name=highlight.$name
  fi
  echo copy $name
  cp output/$name.ref '"$base"'/autotests/reference/
  cp html.output/$name.html html.output/$name.dark.html '"$base"'/autotests/html/
  cp folding.out/$name.fold '"$base"'/autotests/folding/
done' > update-reference-data.sh

echo '#!/bin/sh
XDG_DATA_DIRS='"$d"' ~/game/ksyntax-trace/kate-syntax-highlighter --output-format=ansi256colors -tMy\ Breeze\ Dark "$@"' > hi.sh

echo '#!/bin/sh
XDG_DATA_DIRS='"$d"' ~/game/ksyntax-trace/kate-syntax-highlighter --output-format=ansi256colors -tMy\ Breeze\ Dark --stdin -s "$@"' > ihi.sh

echo '#!/bin/sh
XDG_DATA_DIRS='"$d"' ~/game/ksyntax-trace/kate-syntax-highlighter --output-format=ansi256colors -ntMy\ Breeze\ Dark "$@"' > nhi.sh

echo '#!/bin/sh
XDG_DATA_DIRS='"$d"' ~/game/ksyntax-trace/kate-syntax-highlighter --output-format=ansi256colors --syntax-trace=format -tMy\ Breeze\ Dark --stdin -s "$@"' > nihi.sh

echo '#!/bin/sh
XDG_DATA_DIRS='"$d"' ~/game/ksyntax-trace/kate-syntax-highlighter --output-format=ansi256colors --syntax-trace=format --syntax-trace=context -tMy\ Breeze\ Dark "$@"' > thi.sh

echo '#!/bin/sh
XDG_DATA_DIRS='"$d"' ~/game/ksyntax-trace/kate-syntax-highlighter --output-format=ansi256colors --syntax-trace=format --syntax-trace=context -tMy\ Breeze\ Dark --stdin -s "$@"' > tihi.sh

echo '#!/bin/sh
while read l ; do echo "$l" | "$@" ; done' > unbuffered.sh

echo '#!/bin/sh
RLWRAP_HOME='"$d"' rlwrap ./unbuffered.sh "$@"' > rlwrap.sh

echo '#!/bin/sh
XDG_DATA_DIRS='"$d"' kate "$@"' > kate.sh

echo '#!/bin/sh
xmllint --noout --schema '"$base"'/data/schema/language.xsd "$@"' > validatehl.sh

echo '#!/bin/sh
cmake -DCMAKE_BUILD_TYPE=Release "$@" -G Ninja .. && ./test.sh' > build.sh

echo '#!/bin/sh
./validatehl.sh syntax/* && ninja clean && ninja rebuild_cache && ./test.sh' > final.sh

echo '#!/bin/sh
if [[ $# -eq 1 ]]; then
  ninja && XDG_DATA_DIRS='"$d"' ctest --output-on-failure --rerun-failed
else
  ninja && XDG_DATA_DIRS='"$d"' ctest --output-on-failure
fi' > test.sh

chmod +x update-reference-data.sh build.sh test.sh kate.sh validatehl.sh rlwrap.sh \
  hi.sh ihi.sh thi.sh tihi.sh nhi.sh nihi.sh final.sh unbuffered.sh

ln -s "$base"/autotests/input/ "$base"/data/syntax/ .

echo -e '\e[33m'
echo "cd $d/b"
echo './build'
echo './hi.sh input/<file>'
echo './test.sh'
echo './update-reference-data.sh <lang>'
echo

exit $errcode
