#!/usr/bin/env bash

d=~/rawdisk2/sh
dhi="$d/org.kde.syntax-highlighting"

if [ ! -d "$dhi" ] ; then
  mkdir -p "$dhi/syntax" "$dhi/themes"
  cp ~/game/org.kde.syntax-highlighting/themes/my.theme "$dhi/themes"
fi

cd "$(dirname $0)"/../syntax-highlighting/data/syntax
typeset -i errcode=0
for f in "$@"; do
  if [[ ! -f "$f.xml" ]]; then
    echo "$f: file not found"
    ((++errcode))
    continue
  fi

  ln -s "$PWD/$f.xml" "$dhi/syntax" || ((++errcode))
done

exit $errcode
